version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: simplesgestor
      POSTGRES_PASSWORD: senhasegura123
      POSTGRES_DB: simplesgestor
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U simplesgestor -d simplesgestor"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: simplesgestor
      DB_PASSWORD: senhasegura123
      DB_DATABASE: simplesgestor
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./libs:/app/libs
      - /app/node_modules

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4201:4201"
    depends_on:
      - backend
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - ./libs:/app/libs
      - /app/node_modules

  site:
    build:
      context: .
      dockerfile: Dockerfile.site
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ./apps/site:/app/apps/site
      - ./libs:/app/libs
      - /app/node_modules

volumes:
  pg_data:
